[package]
name = "gosub_webinterop"
version = "0.1.1"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"
description = "Web Interop for Gosub"

[dependencies]
syn = { version = "2.0.96", features = ["full", "extra-traits"] }
quote = { version = "1.0.40", features = [] }
proc-macro2 = "1.0.92"
lazy_static = "1.5.0"
cow-utils = "0.1.3"


[lib]
proc-macro = true
