[package]
name = "gosub_shared"
version = "0.1.1"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"
description = "Gosub shared code"

[dependencies]
chardet = "0.2.4"
thiserror = "2.0.11"
url = "2.5.4"
anyhow = "1.0.94"
lazy_static = "1.5.0"
uuid = { version = "1.14.0", features = ["v4"] }
rand = "0.9.0"
chardetng = "0.1.17"
encoding_rs = "0.8.35"
derive_more = {version = "2.0.1", features = ["display"]}
log = "0.4.22"
raw-window-handle = "0.6.2"
smallvec = "1.13.2"
image = "0.25.5"


[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.70"
getrandom = { version = "0.2.15", features = ["js"] }
web-sys = { version = "0.3.72", features = ["Performance", "Window", "Worker", "WorkerOptions", "WorkerType"] }
wasm-bindgen-futures = "0.4.47"
wasm-bindgen = "0.2.93"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = "0.3.31"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"