[package]
name = "gosub_cairo"
version = "0.1.1"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
description = "Cairo render backend for Gosub"
license = "MIT"

[features]
default = ["cairo"]
cairo = ["dep:cairo-rs", "gosub_fontmanager/cairo"]

[dependencies]
gosub_shared = { version = "0.1.1", registry = "gosub", path = "../gosub_shared" }
gosub_interface = { version = "0.1.2", registry = "gosub", path = "../gosub_interface", features = [] }
gosub_svg = { version = "0.1.1", registry = "gosub", path = "../gosub_svg", features = ["resvg"] }
gosub_fontmanager = { version = "0.1.0", path = "../gosub_fontmanager", registry = "gosub", default-features = false }
image = "0.25.6"
smallvec = "1.15.0"
kurbo = "0.11.2"
peniko = "0.3.1"
log = "0.4.27"

# Optional Cairo dependency for Linux/Unix systems  
cairo-rs = { version = "0.19.4", features = ["use_glib", "freetype"], optional = true }
