name: Gosub Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ stable, nightly, 1.73.0 ]
        os: [ ubuntu-24.04 ]
#        rust_version: [ stable, beta, nightly, 1.73.0, "stable minus 1 release", "stable minus 2 releases" ]
#        os: [ ubuntu-24.04, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo/
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-
      - name: Build
        run: cargo build --verbose --all --all-features
      - name: Clean
        run: |
          cargo install cargo-sweep
          cargo sweep --installed
          cargo sweep --time 7

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ stable, nightly, 1.73.0 ]
        os: [ ubuntu-24.04 ]
#        rust_version: [ stable, beta, nightly, 1.73.0, "stable minus 1 release", "stable minus 2 releases" ]
#        os: [ ubuntu-24.04, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-
      - name: Run tests
        run: cargo test --verbose --all --no-fail-fast --all-features --all-targets

  clippy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ stable, nightly ]
        os: [ ubuntu-24.04 ]
#        rust_version: [ stable, beta, nightly, 1.73.0, "stable minus 1 release", "stable minus 2 releases" ]
#        os: [ ubuntu-24.04, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install sqlite3 libsqlite3-dev libglib2.0-dev libcairo2-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libgtk-4-dev -y
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-registry-${{ matrix.rust_version }}-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-target-${{ matrix.rust_version }}-
      - name: Run Clippy
        run: cargo clippy --all --all-targets -- -D warnings

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-registry-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-${{ matrix.rust_version }}-
      - name: Cache cargo build
        uses: actions/cache/restore@v4
        with:
          path: ~/work/gosub-engine/gosub-engine/target
          key: ${{ runner.os }}-cargo-target-${{ matrix.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ matrix.rust_version }}-
      - name: Run fmt
        run: cargo fmt --check --all

  # Windows cross-compilation job
  windows:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y mingw-w64 gcc-mingw-w64-x86-64
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: windows-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            windows-cargo-registry-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: windows-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            windows-cargo-target-
      - name: Build Windows executable
        run: |
          rustup target add x86_64-pc-windows-gnu
          chmod +x build-windows.sh
          ./build-windows.sh
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: target/x86_64-pc-windows-gnu/release/*.exe
          retention-days: 30
